    $surahs = array(
        1 => array('id'=>'1','arabic'=>'الفاتحة','latin'=>'Al-Fatiha','english'=>'The Opening','location'=>'1','sajda'=>'0','aya'=>'7', 'start'=>'1', 'end'=>'1'),
        2 => array('id'=>'2','arabic'=>'البقرة','latin'=>'Al-Baqara','english'=>'The Cow','location'=>'2','sajda'=>'0','aya'=>'286', 'start'=>'2', 'end'=>'49'),
        3 => array('id'=>'3','arabic'=>'آل عمران','latin'=>'Aal-e-Imran','english'=>'The family of Imran','location'=>'2','sajda'=>'0','aya'=>'200', 'start'=>'50', 'end'=>'76'),
        4 => array('id'=>'4','arabic'=>'النساء','latin'=>'An-Nisa','english'=>'The Women','location'=>'2','sajda'=>'0','aya'=>'176', 'start'=>'77', 'end'=>'106'),
        5 => array('id'=>'5','arabic'=>'المائدة','latin'=>'Al-Maeda','english'=>'The Table Spread','location'=>'2','sajda'=>'0','aya'=>'120', 'start'=>'106', 'end'=>'127'),
        6 => array('id'=>'6','arabic'=>'الأنعام','latin'=>'Al-Anaam','english'=>'The cattle','location'=>'1','sajda'=>'0','aya'=>'165', 'start'=>'128', 'end'=>'150'),
        7 => array('id'=>'7','arabic'=>'الأعراف','latin'=>'Al-Araf','english'=>'The heights','location'=>'1','sajda'=>'206','aya'=>'206', 'start'=>'151', 'end'=>'176'),
        8 => array('id'=>'8','arabic'=>'الأنفال','latin'=>'Al-Anfal','english'=>'Spoils of war, booty','location'=>'2','sajda'=>'0','aya'=>'75', 'start'=>'177', 'end'=>'186'),
        9 => array('id'=>'9','arabic'=>'التوبة','latin'=>'At-Taubah','english'=>'Repentance','location'=>'2','sajda'=>'0','aya'=>'129', 'start'=>'187', 'end'=>'207'),
        10 => array('id'=>'10','arabic'=>'يونس','latin'=>'Yunus','english'=>'Jonah','location'=>'1','sajda'=>'0','aya'=>'109', 'start'=>'208', 'end'=>'221'),
        11 => array('id'=>'11','arabic'=>'هود','latin'=>'Hud','english'=>'Hud','location'=>'1','sajda'=>'0','aya'=>'123', 'start'=>'221', 'end'=>'235'),
        12 => array('id'=>'12','arabic'=>'يوسف','latin'=>'Yusuf','english'=>'Joseph','location'=>'1','sajda'=>'0','aya'=>'111', 'start'=>'235', 'end'=>'248'),
        13 => array('id'=>'13','arabic'=>'الرعد','latin'=>'Ar-Rad','english'=>'The Thunder','location'=>'1','sajda'=>'15','aya'=>'43', 'start'=>'249', 'end'=>'255'),
        14 => array('id'=>'14','arabic'=>'إبراهيم','latin'=>'Ibrahim','english'=>'Abraham','location'=>'1','sajda'=>'0','aya'=>'52', 'start'=>'255', 'end'=>'261'),
        15 => array('id'=>'15','arabic'=>'الحجر','latin'=>'Al-Hijr','english'=>'Stoneland, Rock city, Al-Hijr valley','location'=>'1','sajda'=>'0','aya'=>'99', 'start'=>'262', 'end'=>'267'),
        16 => array('id'=>'16','arabic'=>'النحل','latin'=>'An-Nahl','english'=>'The Bee','location'=>'1','sajda'=>'50','aya'=>'128', 'start'=>'267', 'end'=>'281'),
        17 => array('id'=>'17','arabic'=>'الإسراء','latin'=>'Al-Isra','english'=>'The night journey','location'=>'1','sajda'=>'100','aya'=>'111', 'start'=>'282', 'end'=>'293'),
        18 => array('id'=>'18','arabic'=>'الكهف','latin'=>'Al-Kahf','english'=>'The cave','location'=>'1','sajda'=>'0','aya'=>'110', 'start'=>'293', 'end'=>'304'),
        19 => array('id'=>'19','arabic'=>'مريم','latin'=>'Maryam','english'=>'Mary','location'=>'1','sajda'=>'58','aya'=>'98', 'start'=>'305', 'end'=>'312'),
        20 => array('id'=>'20','arabic'=>'طه','latin'=>'Taha','english'=>'Taha','location'=>'1','sajda'=>'0','aya'=>'135', 'start'=>'312', 'end'=>'321'),
        21 => array('id'=>'21','arabic'=>'الأنبياء','latin'=>'Al-Anbiya','english'=>'The Prophets','location'=>'1','sajda'=>'0','aya'=>'112', 'start'=>'322', 'end'=>'331'),
        22 => array('id'=>'22','arabic'=>'الحج','latin'=>'Al-Hajj','english'=>'The Pilgrimage','location'=>'1','sajda'=>'18','aya'=>'78', 'start'=>'332', 'end'=>'341'),
        23 => array('id'=>'23','arabic'=>'المؤمنون','latin'=>'Al-Mumenoon','english'=>'The Believers','location'=>'1','sajda'=>'0','aya'=>'118', 'start'=>'342', 'end'=>'349'),
        24 => array('id'=>'24','arabic'=>'النور','latin'=>'An-Noor','english'=>'The Light','location'=>'1','sajda'=>'0','aya'=>'64', 'start'=>'350', 'end'=>'359'),
        25 => array('id'=>'25','arabic'=>'الفرقان','latin'=>'Al-Furqan','english'=>'The Standard','location'=>'1','sajda'=>'60','aya'=>'77', 'start'=>'359', 'end'=>'366'),
        26 => array('id'=>'26','arabic'=>'الشعراء','latin'=>'Ash-Shuara','english'=>'The Poets','location'=>'1','sajda'=>'0','aya'=>'227', 'start'=>'367', 'end'=>'376'),
        27 => array('id'=>'27','arabic'=>'النمل','latin'=>'An-Naml','english'=>'THE ANT','location'=>'1','sajda'=>'26','aya'=>'93', 'start'=>'377', 'end'=>'385'),
        28 => array('id'=>'28','arabic'=>'القصص','latin'=>'Al-Qasas','english'=>'The Story','location'=>'1','sajda'=>'0','aya'=>'88', 'start'=>'385', 'end'=>'396'),
        29 => array('id'=>'29','arabic'=>'العنكبوت','latin'=>'Al-Ankaboot','english'=>'The Spider','location'=>'1','sajda'=>'0','aya'=>'69', 'start'=>'396', 'end'=>'404'),
        30 => array('id'=>'30','arabic'=>'الروم','latin'=>'Ar-Room','english'=>'The Romans','location'=>'1','sajda'=>'0','aya'=>'60', 'start'=>'404', 'end'=>'410'),
        31 => array('id'=>'31','arabic'=>'لقمان','latin'=>'Luqman','english'=>'Luqman','location'=>'1','sajda'=>'0','aya'=>'34', 'start'=>'411', 'end'=>'414'),
        32 => array('id'=>'32','arabic'=>'السجدة','latin'=>'As-Sajda','english'=>'The Prostration','location'=>'1','sajda'=>'15','aya'=>'30', 'start'=>'415', 'end'=>'417'),
        33 => array('id'=>'33','arabic'=>'الأحزاب','latin'=>'Al-Ahzab','english'=>'The Coalition','location'=>'1','sajda'=>'0','aya'=>'73', 'start'=>'418', 'end'=>'427'),
        34 => array('id'=>'34','arabic'=>'سبأ','latin'=>'Saba','english'=>'Saba','location'=>'1','sajda'=>'0','aya'=>'54', 'start'=>'428', 'end'=>'434'),
        35 => array('id'=>'35','arabic'=>'فاطر','latin'=>'Fatir','english'=>'Originator','location'=>'1','sajda'=>'0','aya'=>'45', 'start'=>'434', 'end'=>'440'),
        36 => array('id'=>'36','arabic'=>'يس','latin'=>'Ya Seen','english'=>'Ya Seen','location'=>'1','sajda'=>'0','aya'=>'83', 'start'=>'440', 'end'=>'445'),
        37 => array('id'=>'37','arabic'=>'الصافات','latin'=>'As-Saaffat','english'=>'Those who set the ranks','location'=>'1','sajda'=>'0','aya'=>'182', 'start'=>'446', 'end'=>'452'),
        38 => array('id'=>'38','arabic'=>'ص','latin'=>'Sad','english'=>'Sad','location'=>'1','sajda'=>'24','aya'=>'88', 'start'=>'453', 'end'=>'458'),
        39 => array('id'=>'39','arabic'=>'الزمر','latin'=>'Az-Zumar','english'=>'The Troops','location'=>'1','sajda'=>'0','aya'=>'75', 'start'=>'458', 'end'=>'467'),
        40 => array('id'=>'40','arabic'=>'غافر','latin'=>'Ghafir','english'=>'The Forgiver','location'=>'1','sajda'=>'0','aya'=>'85', 'start'=>'467', 'end'=>'476'),
        41 => array('id'=>'41','arabic'=>'فصلت','latin'=>'Fussilat','english'=>'Explained in detail','location'=>'1','sajda'=>'38','aya'=>'54', 'start'=>'477', 'end'=>'482'),
        42 => array('id'=>'42','arabic'=>'الشورى','latin'=>'Ash-Shura','english'=>'Council, Consultation','location'=>'1','sajda'=>'0','aya'=>'53', 'start'=>'483', 'end'=>'489'),
        43 => array('id'=>'43','arabic'=>'الزخرف','latin'=>'Az-Zukhruf','english'=>'Ornaments of Gold','location'=>'1','sajda'=>'0','aya'=>'89', 'start'=>'489', 'end'=>'495'),
        44 => array('id'=>'44','arabic'=>'الدخان','latin'=>'Ad-Dukhan','english'=>'The Smoke','location'=>'1','sajda'=>'0','aya'=>'59', 'start'=>'496', 'end'=>'498'),
        45 => array('id'=>'45','arabic'=>'الجاثية','latin'=>'Al-Jathiya','english'=>'Crouching','location'=>'1','sajda'=>'0','aya'=>'37', 'start'=>'499', 'end'=>'502'),
        46 => array('id'=>'46','arabic'=>'الأحقاف','latin'=>'Al-Ahqaf','english'=>'The wind-curved sandhills','location'=>'1','sajda'=>'0','aya'=>'35', 'start'=>'502', 'end'=>'506'),
        47 => array('id'=>'47','arabic'=>'محمد','latin'=>'Muhammad','english'=>'Muhammad','location'=>'2','sajda'=>'0','aya'=>'38', 'start'=>'507', 'end'=>'510'),
        48 => array('id'=>'48','arabic'=>'الفتح','latin'=>'Al-Fath','english'=>'The victory','location'=>'2','sajda'=>'0','aya'=>'29', 'start'=>'511', 'end'=>'515'),
        49 => array('id'=>'49','arabic'=>'الحجرات','latin'=>'Al-Hujraat','english'=>'The private apartments','location'=>'2','sajda'=>'0','aya'=>'18', 'start'=>'515', 'end'=>'517'),
        50 => array('id'=>'50','arabic'=>'ق','latin'=>'Qaf','english'=>'Qaf','location'=>'1','sajda'=>'0','aya'=>'45', 'start'=>'518', 'end'=>'520'),
        51 => array('id'=>'51','arabic'=>'الذاريات','latin'=>'Adh-Dhariyat','english'=>'The winnowing winds','location'=>'1','sajda'=>'0','aya'=>'60', 'start'=>'520', 'end'=>'523'),
        52 => array('id'=>'52','arabic'=>'الطور','latin'=>'At-tur','english'=>'Mount Sinai','location'=>'1','sajda'=>'0','aya'=>'49', 'start'=>'523', 'end'=>'525'),
        53 => array('id'=>'53','arabic'=>'النجم','latin'=>'An-Najm','english'=>'The Star','location'=>'1','sajda'=>'62','aya'=>'62', 'start'=>'526', 'end'=>'528'),
        54 => array('id'=>'54','arabic'=>'القمر','latin'=>'Al-Qamar','english'=>'The moon','location'=>'1','sajda'=>'0','aya'=>'55', 'start'=>'528', 'end'=>'531'),
        55 => array('id'=>'55','arabic'=>'الرحمن','latin'=>'Al-Rahman','english'=>'The Beneficient','location'=>'1','sajda'=>'0','aya'=>'78', 'start'=>'531', 'end'=>'534'),
        56 => array('id'=>'56','arabic'=>'الواقعة','latin'=>'Al-Waqia','english'=>'The Event, The Inevitable','location'=>'1','sajda'=>'0','aya'=>'96', 'start'=>'534', 'end'=>'537'),
        57 => array('id'=>'57','arabic'=>'الحديد','latin'=>'Al-Hadid','english'=>'The Iron','location'=>'2','sajda'=>'0','aya'=>'29', 'start'=>'537', 'end'=>'541'),
        58 => array('id'=>'58','arabic'=>'المجادلة','latin'=>'Al-Mujadila','english'=>'She that disputes','location'=>'2','sajda'=>'0','aya'=>'22', 'start'=>'542', 'end'=>'545'),
        59 => array('id'=>'59','arabic'=>'الحشر','latin'=>'Al-Hashr','english'=>'Exile','location'=>'2','sajda'=>'0','aya'=>'24', 'start'=>'545', 'end'=>'548'),
        60 => array('id'=>'60','arabic'=>'الممتحنة','latin'=>'Al-Mumtahina','english'=>'She that is to be examined','location'=>'2','sajda'=>'0','aya'=>'13', 'start'=>'549', 'end'=>'551'),
        61 => array('id'=>'61','arabic'=>'الصف','latin'=>'As-Saff','english'=>'The Ranks','location'=>'2','sajda'=>'0','aya'=>'14', 'start'=>'551', 'end'=>'552'),
        62 => array('id'=>'62','arabic'=>'الجمعة','latin'=>'Al-Jumua','english'=>'The congregation, Friday','location'=>'2','sajda'=>'0','aya'=>'11', 'start'=>'553', 'end'=>'554'),
        63 => array('id'=>'63','arabic'=>'المنافقون','latin'=>'Al-Munafiqoon','english'=>'The Hypocrites','location'=>'2','sajda'=>'0','aya'=>'11', 'start'=>'554', 'end'=>'555'),
        64 => array('id'=>'64','arabic'=>'التغابن','latin'=>'At-Taghabun','english'=>'Mutual Disillusion','location'=>'2','sajda'=>'0','aya'=>'18', 'start'=>'556', 'end'=>'557'),
        65 => array('id'=>'65','arabic'=>'الطلاق','latin'=>'At-Talaq','english'=>'Divorce','location'=>'2','sajda'=>'0','aya'=>'12', 'start'=>'558', 'end'=>'559'),
        66 => array('id'=>'66','arabic'=>'التحريم','latin'=>'At-Tahrim','english'=>'Banning','location'=>'2','sajda'=>'0','aya'=>'12', 'start'=>'560', 'end'=>'561'),
        67 => array('id'=>'67','arabic'=>'الملك','latin'=>'Al-Mulk','english'=>'The Sovereignty','location'=>'1','sajda'=>'0','aya'=>'30', 'start'=>'562', 'end'=>'564'),
        68 => array('id'=>'68','arabic'=>'القلم','latin'=>'Al-Qalam','english'=>'The Pen','location'=>'1','sajda'=>'0','aya'=>'52', 'start'=>'564', 'end'=>'566'),
        69 => array('id'=>'69','arabic'=>'الحاقة','latin'=>'Al-Haaqqa','english'=>'The reality','location'=>'1','sajda'=>'0','aya'=>'52', 'start'=>'566', 'end'=>'568'),
        70 => array('id'=>'70','arabic'=>'المعارج','latin'=>'Al-Maarij','english'=>'The Ascending stairways','location'=>'1','sajda'=>'0','aya'=>'44', 'start'=>'568', 'end'=>'570'),
        71 => array('id'=>'71','arabic'=>'نوح','latin'=>'Nooh','english'=>'Nooh','location'=>'1','sajda'=>'0','aya'=>'28', 'start'=>'570', 'end'=>'571'),
        72 => array('id'=>'72','arabic'=>'الجن','latin'=>'Al-Jinn','english'=>'The Jinn','location'=>'1','sajda'=>'0','aya'=>'28', 'start'=>'572', 'end'=>'573'),
        73 => array('id'=>'73','arabic'=>'المزمل','latin'=>'Al-Muzzammil','english'=>'The enshrouded one','location'=>'1','sajda'=>'0','aya'=>'20', 'start'=>'574', 'end'=>'575'),
        74 => array('id'=>'74','arabic'=>'المدثر','latin'=>'Al-Muddathir','english'=>'The cloaked one','location'=>'1','sajda'=>'0','aya'=>'56', 'start'=>'575', 'end'=>'577'),
        75 => array('id'=>'75','arabic'=>'القيامة','latin'=>'Al-Qiyama','english'=>'The rising of the dead','location'=>'1','sajda'=>'0','aya'=>'40', 'start'=>'577', 'end'=>'578'),
        76 => array('id'=>'76','arabic'=>'الإنسان','latin'=>'Al-Insan','english'=>'The man','location'=>'2','sajda'=>'0','aya'=>'31', 'start'=>'578', 'end'=>'580'),
        77 => array('id'=>'77','arabic'=>'المرسلات','latin'=>'Al-Mursalat','english'=>'The emissaries','location'=>'1','sajda'=>'0','aya'=>'50', 'start'=>'580', 'end'=>'581'),
        78 => array('id'=>'78','arabic'=>'النبأ','latin'=>'An-Naba','english'=>'The tidings','location'=>'1','sajda'=>'0','aya'=>'40', 'start'=>'582', 'end'=>'583'),
        79 => array('id'=>'79','arabic'=>'النازعات','latin'=>'An-Naziat','english'=>'Those who drag forth','location'=>'1','sajda'=>'0','aya'=>'46', 'start'=>'583', 'end'=>'584'),
        80 => array('id'=>'80','arabic'=>'عبس','latin'=>'Abasa','english'=>'He Frowned','location'=>'1','sajda'=>'0','aya'=>'42', 'start'=>'585', 'end'=>'586'),
        81 => array('id'=>'81','arabic'=>'التكوير','latin'=>'At-Takwir','english'=>'The Overthrowing','location'=>'1','sajda'=>'0','aya'=>'29', 'start'=>'586', 'end'=>'586'),
        82 => array('id'=>'82','arabic'=>'الإنفطار','latin'=>'AL-Infitar','english'=>'The Cleaving','location'=>'1','sajda'=>'0','aya'=>'19', 'start'=>'587', 'end'=>'587'),
        83 => array('id'=>'83','arabic'=>'المطففين','latin'=>'Al-Mutaffifin','english'=>'Defrauding','location'=>'1','sajda'=>'0','aya'=>'36', 'start'=>'587', 'end'=>'589'),
        84 => array('id'=>'84','arabic'=>'الانشقاق','latin'=>'Al-Inshiqaq','english'=>'The Sundering, Splitting Open','location'=>'1','sajda'=>'21','aya'=>'25', 'start'=>'589', 'end'=>'590'),
        85 => array('id'=>'85','arabic'=>'البروج','latin'=>'Al-Burooj','english'=>'The Mansions of the stars','location'=>'1','sajda'=>'0','aya'=>'22', 'start'=>'590', 'end'=>'590'),
        86 => array('id'=>'86','arabic'=>'الطارق','latin'=>'At-Tariq','english'=>'The morning star','location'=>'1','sajda'=>'0','aya'=>'17', 'start'=>'591', 'end'=>'591'),
        87 => array('id'=>'87','arabic'=>'الأعلى','latin'=>'Al-Ala','english'=>'The Most High','location'=>'1','sajda'=>'0','aya'=>'19', 'start'=>'591', 'end'=>'592'),
        88 => array('id'=>'88','arabic'=>'الغاشية','latin'=>'Al-Ghashiya','english'=>'The Overwhelming','location'=>'1','sajda'=>'0','aya'=>'26', 'start'=>'592', 'end'=>'593'),
        89 => array('id'=>'89','arabic'=>'الفجر','latin'=>'Al-Fajr','english'=>'The Dawn','location'=>'1','sajda'=>'0','aya'=>'30', 'start'=>'593', 'end'=>'594'),
        90 => array('id'=>'90','arabic'=>'البلد','latin'=>'Al-Balad','english'=>'The City','location'=>'1','sajda'=>'0','aya'=>'20', 'start'=>'594', 'end'=>'595'),
        91 => array('id'=>'91','arabic'=>'الشمس','latin'=>'Ash-Shams','english'=>'The Sun','location'=>'1','sajda'=>'0','aya'=>'15', 'start'=>'595', 'end'=>'595'),
        92 => array('id'=>'92','arabic'=>'الليل','latin'=>'Al-Lail','english'=>'The night','location'=>'1','sajda'=>'0','aya'=>'21', 'start'=>'595', 'end'=>'596'),
        93 => array('id'=>'93','arabic'=>'الضحى','latin'=>'Ad-Dhuha','english'=>'The morning hours','location'=>'1','sajda'=>'0','aya'=>'11', 'start'=>'596', 'end'=>'596'),
        94 => array('id'=>'94','arabic'=>'الشرح','latin'=>'Al-Inshirah','english'=>'Solace','location'=>'1','sajda'=>'0','aya'=>'8', 'start'=>'596', 'end'=>'597'),
        95 => array('id'=>'95','arabic'=>'التين','latin'=>'At-Tin','english'=>'The Fig','location'=>'1','sajda'=>'0','aya'=>'8', 'start'=>'597', 'end'=>'597'),
        96 => array('id'=>'96','arabic'=>'العلق','latin'=>'Al-Alaq','english'=>'The Clot','location'=>'1','sajda'=>'19','aya'=>'19', 'start'=>'597', 'end'=>'598'),
        97 => array('id'=>'97','arabic'=>'القدر','latin'=>'Al-Qadr','english'=>'The Power','location'=>'1','sajda'=>'0','aya'=>'5', 'start'=>'598', 'end'=>'598'),
        98 => array('id'=>'98','arabic'=>'البينة','latin'=>'Al-Bayyina','english'=>'The Clear proof','location'=>'2','sajda'=>'0','aya'=>'8', 'start'=>'598', 'end'=>'599'),
        99 => array('id'=>'99','arabic'=>'الزلزلة','latin'=>'Al-Zalzala','english'=>'The earthquake','location'=>'2','sajda'=>'0','aya'=>'8', 'start'=>'599', 'end'=>'599'),
        100 => array('id'=>'100','arabic'=>'العاديات','latin'=>'Al-Adiyat','english'=>'The Chargers','location'=>'1','sajda'=>'0','aya'=>'11', 'start'=>'599', 'end'=>'600'),
        101 => array('id'=>'101','arabic'=>'القارعة','latin'=>'Al-Qaria','english'=>'The Calamity','location'=>'1','sajda'=>'0','aya'=>'11', 'start'=>'600', 'end'=>'600'),
        102 => array('id'=>'102','arabic'=>'التكاثر','latin'=>'At-Takathur','english'=>'Competition','location'=>'1','sajda'=>'0','aya'=>'8', 'start'=>'600', 'end'=>'600'),
        103 => array('id'=>'103','arabic'=>'العصر','latin'=>'Al-Asr','english'=>'The declining day','location'=>'1','sajda'=>'0','aya'=>'3' , 'start'=>'601', 'end'=>'601'),
        104 => array('id'=>'104','arabic'=>'الهمزة','latin'=>'Al-Humaza','english'=>'The Traducer','location'=>'1','sajda'=>'0','aya'=>'9' , 'start'=>'601', 'end'=>'601'),
        105 => array('id'=>'105','arabic'=>'الفيل','latin'=>'Al-fil','english'=>'The Elephant','location'=>'1','sajda'=>'0','aya'=>'5' , 'start'=>'601', 'end'=>'601'),
        106 => array('id'=>'106','arabic'=>'قريش','latin'=>'Quraish','english'=>'Quraish','location'=>'1','sajda'=>'0','aya'=>'4', 'start'=>'602', 'end'=>'602'),
        107 => array('id'=>'107','arabic'=>'الماعون','latin'=>'Al-Maun','english'=>'Alms Giving','location'=>'1','sajda'=>'0','aya'=>'7', 'start'=>'602', 'end'=>'602'),
        108 => array('id'=>'108','arabic'=>'الكوثر','latin'=>'Al-Kauther','english'=>'Abundance','location'=>'1','sajda'=>'0','aya'=>'3', 'start'=>'602', 'end'=>'602'),
        109 => array('id'=>'109','arabic'=>'الكافرون','latin'=>'Al-Kafiroon','english'=>'The Disbelievers','location'=>'1','sajda'=>'0','aya'=>'6', 'start'=>'603', 'end'=>'603'),
        110 => array('id'=>'110','arabic'=>'النصر','latin'=>'An-Nasr','english'=>'The Succour','location'=>'2','sajda'=>'0','aya'=>'3', 'start'=>'603', 'end'=>'603'),
        111 => array('id'=>'111','arabic'=>'المسد','latin'=>'Al-Masadd','english'=>'The Flame','location'=>'1','sajda'=>'0','aya'=>'5', 'start'=>'603', 'end'=>'603'),
        112 => array('id'=>'112','arabic'=>'الإخلاص','latin'=>'Al-Ikhlas','english'=>'Absoluteness','location'=>'1','sajda'=>'0','aya'=>'4', 'start'=>'600', 'end'=>'600'),
        113 => array('id'=>'113','arabic'=>'الفلق','latin'=>'Al-Falaq','english'=>'The day break','location'=>'1','sajda'=>'0','aya'=>'5', 'start'=>'600', 'end'=>'600'),
        114 => array('id'=>'114','arabic'=>'الناس','latin'=>'An-Nas','english'=>'The mankind','location'=>'1','sajda'=>'0','aya'=>'6', 'start'=>'600', 'end'=>'600')
    );
